### ISSUE TITLE
Revise and rewrite database persistence logic

### ISSUE THREAD

**Issue by azinneera** [wso2-incubator/testgrid#242]
**Description:**
The database design should be revised according to the dashboard requirements.

**Suggested Labels:**
Type/Task

**Suggested Assignees:**
AsmaJ

**Comment by vidurananayakkara** [comment]
The discussed ERD is as shown below:

![image](https://user-images.githubusercontent.com/8591787/34153143-10286ef4-e4d7-11e7-8a2d-e0929c9da383.png)

**Comment by azinneera** [comment]
Done
