### ISSUE TITLE
Generalizing Infrastructure automation in TestGrid

### ISSUE THREAD

**Issue by harshanL** [wso2-incubator/testgrid#28]
**Description:**
This includes automating the infrastructure creation through testgrid framework itself using the config provided and designing the infrastructure configuration schema.

**Comment by kasunbg** [comment]
@harshanL shall we also add why this is in blocked state here as well?

**Comment by harshanL** [comment]
We are unable to proceed with this task until the separation of infrastructure from deployment has finalized.

**Comment by vidurananayakkara** [comment]
Closing issue since infrastructure automation is not a responsibility of TestGrid anymore. Creation of the infrastructure should be handled by the end user via the provided shell script.
