### ISSUE TITLE
Fetch product channels periodically from PMT Channel-Info endpoint and generate TestGrid jobs..

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/testgrid#286]
**Description:**
Introduce a subscriber (JMS/periodic poller) that fetch product channel information from a channel-info endpoint. This endpoint does not exist ATM. We should create a dummy endpoint.

The channel-info endpoint will provide details on new product additions including all its channels, removal/update of channels.

More info can be found here: https://github.com/wso2-incubator/testgrid/issues/283

**Related Issues:**
https://github.com/wso2-incubator/testgrid/issues/283

**Comment by pasindujw** [comment]
Not applicable as per recent discussion, TestGrid will be providing a common API to external parties and its their responsibility to send the updates properly to TestGrid.
Hence closing.
