### ISSUE TITLE
Evaluate messaging frameworks that fits with Testgrid usecases

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/testgrid#315]
**Description:**
TestGrid works in collaboration with PMT, WUM, and bunch of other systems. 
We need to decide how the communication between these sub-systems will happen. 

We have requirements to receice notifications from these sub-systems. One such usecase is receive new product, version, and channel additions. So, we need to evaluate what makes most sense here. 

List of frameworks to evaluate:
1. Kafka
2. Amazon SNS/SQS
3. JMS/AMQP/MQTT
4. Periodic polling

We need to take this decision in collaboration with all parties in the system. 

We need to do the initial research ASAP. 

**Related Issues:**
Todo
Update channel info in TestGrid
Trigger testruns for new WUM updates.

**Comment by vidurananayakkara** [comment]
Closing since TestGrid do not need to know (or is not aware of) any WUM related information

**Comment by kasunbg** [comment]
Not applicable anymore.
