### ISSUE TITLE
Identify the hardware resource requirements to the TestGrid development and Test run environments 

### ISSUE THREAD

**Issue by WarunaD** [wso2-incubator/testgrid#33]
**Description:**
Identify the hardware resource requirements to the TestGrid development and Test run environments

**Comment by kasunbg** [comment]
TestGrid deployment will be built on top of Jenkins. We are thinking to use AWS m3.large EC2 instance for Jenkins master and a set of slave nodes dynamically provisioned via AWS EC2 Container Service of size m3.large.
