### ISSUE TITLE
Enable https for TestGrid dashboard

### ISSUE THREAD

**Issue by kasunbg** [wso2-incubator/testgrid#347]
**Description:**
As the first line of defence, we should enable https for the TestGrid deployment.

**Affected Product Version:**
0.9-m8

**Steps to reproduce:**
N/A

**Related Issues:**
#297

**Comment by kasunbg** [comment]
As part of this effort, we should get TestGrid to run against the default https/443 port. 

We can easily enable https via tomcat server.xml. But, we need to run Tomcat as a normal user though. A normal user does not have privileges to bind to port 443. Hence, we have to find options we have:

1. Enable port-forwarding via `iptables` where we forward traffic to 443 to port 8443.
2. Add a reverse-proxy such as httpd/nginx 
3. Run tomcat in sudoer mode.

Option #3 is not really an option for us. #2 may be an over-kill. Hence, IMO we should go with #1.

**Comment by yasassri** [comment]
#2 will allow us to handle production environment migration smoothly without any downtime, also If we want to scale for high availability having an LB would be advantageous.

**Comment by yasassri** [comment]
This is done in the Dev environment, and currently waiting for a CA-signed cert.

**Comment by yasassri** [comment]
This is completed in both dev and prod.
